- CropRunner.py
- PanoScraper.py
- scrape_and_crop_labels.py
- test.py
Resolves #1 
Parallelizes the pano scraping and label image cropping pipelines.
> Parallel scraper

- eval.py
Added a script allowing us to evaluate models on the test set and view metrics such as test accuracy/loss and a confusion matrix over classes.
> Added Eval Script

- analyze_results.py
- eval.py
- train.py
- utils/training_utils.py
Resolves #25 
Modularizes the pre-trained model instantiation. Also cleans up train/eval/training util scripts for easier training and navigability.
> Modularize pretrained model setup

- CropRunner.py
- PanoScraper.py
Resolves #34 
This PR fixes the cropping of labels near the sides of the panorama to ultimately remove the resulting black space.
Before:
After:
> 34 Fixed cropping of labels near the sides of the panorama

- analyze_results.py
- train.py
- train_binary.py
- utils/binary_relabeler.py
- utils/training_utils.py
Resolves #3 
Adds support to help train a binary classifier via a data modifier (multi-class to binary class) and an independent training script to keep them modularized.
> Support Binary Classification Learning

- utils/dataset_splitter.py
Resolves #45 
Adds code in `dataset_splitter.py` to split the dataset into smaller and larger crops.
> Adds a method to split dataset into large and small crops

- README.md
Pulling changes to see on github pages
> testing formatting changes

- utils/interactive_dataset_creater.py
Adds an interactive dataset csv builder tool. Operations it currently supports are combining, binarizing, subsetting, and city labelling. Note that it doesn't have very good error handling at this time.
> Add Interactive Dataset Creater tool

- eval.py
- visualization_utils/visualize_mistakes.py
adds borders, cropping, and separation between false positives and false negatives to visualization of mistakes
> updated viz logic

- testset_maker/init_testset.py
- testset_maker/server_tool.py
Introduces "testset_maker" directory with two new files:
- "init_testset.py" for generating a new test set.
- "server-tool.py" for clicking through crops and editing the test set.
Here's what it looks like:
> Interactive Visualization Tool for Creating and Editing the Test Set

- utils/interactive_dataset_creator.py
> Fixed filter command

- utils/interactive_dataset_creator.py
Adds functionality to check if one dataframe is a subset of another via an inner join.
> Inner join check to see if DF is subset of another

- scrape_and_crop_labels.py
Added filtering of deleted and tutorial labels in the cropping methodology.
> Add filter for deleted and tutorial labels

- CropRunner.py
- PanoScraper.py
- datatypes/label.py
- scrape_and_crop_labels.py
Makes the cropping process slightly less error prone and also outputs more relevant information for experimentation.
> Make cropping safer

- train.py
- utils/dataset_creator.py
Adds a validate operation to the dataset creator tool. 
Currently it's named kind of poorly since it's not really validating but instead flagging positively validated crops, but we can decide on a better name later.
Also adds more filter options in the filter command.
Additional small changes include some small QoL changes in the dataset creator for usability and changing the StepLR stepsize to 3 epochs rather than 10.
> Add Validate Operation to Dataset Creator

- experiments/experiment3_1.sh
- experiments/experiment3_2.sh
- experiments/experiment3_3.sh
Cleaned up experiments as discussed.
> Cleaned up experiments.

- utils/server_tool.py
> Refactored server tool to operate from the crops directory

- utils/server_tool.py
> implements bounding box

- experiments/experiment2_1.sh
- utils/dataset_creator.py
Adds experiment script for experiment 2.1. 
Also adds command-line dataset_creator functionality in validate and filter
> Added experiment script for 2.1

- datatypes/uniform_sampler.py
- train.py
- utils/training_utils.py
Implements a uniform sampler so that at every epoch, we have equal number of positive/negative classes (in total, two times the cardinality of the minority class).
> Uniform sampling

- experiments/experiment2_1.sh
- experiments/experiment3_0.sh
- experiments/experiment3_1.sh
Updates experiment scripts 2.1, 3.0, 3.1 to use the session name identifier for experimental runs. Also patches small details.
> Update Scripts with Session Name Identifier
